### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by TasselLeer** [wangyaxin1998/RPC#1]
请问你买了rpc这个课吗，感觉好吗

**Comment by wangyaxin1998** [comment]
> 

讲的还不错

**Comment by TasselLeer** [comment]
老哥，可以有偿一起看嘛，我已经秋招结束了但是想学学，价格太贵了

**Comment by wangyaxin1998** [comment]
> 老哥，可以有偿一起看嘛，我已经秋招结束了但是想学学，价格太贵了

www.wyxcloud.asia 我的博客 有我联系方式
